export const businesses = [
    {
        name: "Torrens Arms",
        location: "Mitcham",
        venueType: "Pub",
        openTime: "10am",
        closeTime: "10pm",
        categories: ["Food", "Drink", "Live Music"],
    },
    {
        name: "Marion Hotel",
        location: "Marion",
        venueType: "Pub",
        openTime: "10am",
        closeTime: "10pm",
        categories: ["Food", "Drink", "Live Music"],
    },
    {
        name: "Mylk",
        location: "Adelaide CBD",
        venueType: "Restaurant",
        openTime: "10am",
        closeTime: "10pm",
        categories: ["Food", "Drink", "Live Music", "Family"],
    },
    {
        name: "Hacienda",
        location: "Adelaide CBD",
        venueType: "Bar",
        openTime: "10am",
        closeTime: "10pm",
        categories: ["Drink", "Dance"],
    },
    {
        name: "Marion Hotel",
        location: "Marion",
        venueType: "Pub",
        openTime: "10am",
        closeTime: "10pm",
        categories: ["Food", "Drink", "Live Music"],
    },
    {
        name: "Mylk",
        location: "Adelaide CBD",
        venueType: "Restaurant",
        openTime: "10am",
        closeTime: "10pm",
        categories: ["Food", "Drink", "Live Music", "Family"],
    },
    {
        name: "Hacienda",
        location: "Adelaide CBD",
        venueType: "Bar",
        openTime: "10am",
        closeTime: "10pm",
        categories: ["Drink", "Dance"],
    },
    {
        name: "Marion Hotel",
        location: "Marion",
        venueType: "Pub",
        openTime: "10am",
        closeTime: "10pm",
        categories: ["Food", "Drink", "Live Music"],
    },
    {
        name: "Mylk",
        location: "Adelaide CBD",
        venueType: "Restaurant",
        openTime: "10am",
        closeTime: "10pm",
        categories: ["Food", "Drink", "Live Music", "Family"],
    },
    {
        name: "Hacienda",
        location: "Adelaide CBD",
        venueType: "Bar",
        openTime: "10am",
        closeTime: "10pm",
        categories: ["Drink", "Dance"],
    },
];
