export const businesses = [
    {
        businessId: "1234",
        name: "Torrens Armss",
        location: "Mitcham",
        venueType: "Pub",
        openTime: "10am",
        closeTime: "10pm",
        categories: ["Food", "Drink", "Live Music"],
    },
    {
        businessId: "12234",
        name: "Marion Hotell",
        location: "Marion",
        venueType: "Pub",
        openTime: "10am",
        closeTime: "10pm",
        categories: ["Food", "Drink", "Live Music"],
    },
    {
        businessId: "5434",
        name: "Mylks",
        location: "Adelaide CBD",
        venueType: "Restaurant",
        openTime: "10am",
        closeTime: "10pm",
        categories: ["Food", "Drink", "Live Music", "Family"],
    },
    {
        businessId: "645674",
        name: "Haciendaa",
        location: "Adelaide CBD",
        venueType: "Bar",
        openTime: "10am",
        closeTime: "10pm",
        categories: ["Drink", "Dance"],
    },
    {
        businessId: "787878",
        name: "Marion Hotele",
        location: "Marion",
        venueType: "Pub",
        openTime: "10am",
        closeTime: "10pm",
        categories: ["Food", "Drink", "Live Music"],
    },
    {
        businessId: "1111",
        name: "Mylk",
        location: "Adelaide CBD",
        venueType: "Restaurant",
        openTime: "10am",
        closeTime: "10pm",
        categories: ["Food", "Drink", "Live Music", "Family"],
    },
    {
        businessId: "65554",
        name: "Hacienda",
        location: "Adelaide CBD",
        venueType: "Bar",
        openTime: "10am",
        closeTime: "10pm",
        categories: ["Drink", "Dance"],
    },
    {
        businessId: "234234",
        name: "Marion Hotel",
        location: "Marion",
        venueType: "Pub",
        openTime: "10am",
        closeTime: "10pm",
        categories: ["Food", "Drink", "Live Music"],
    },
    {
        businessId: "87767",
        name: "Mylke",
        location: "Adelaide CBD",
        venueType: "Restaurant",
        openTime: "10am",
        closeTime: "10pm",
        categories: ["Food", "Drink", "Live Music", "Family"],
    },
    {
        businessId: "65437",
        name: "Haciendar",
        location: "Adelaide CBD",
        venueType: "Bar",
        openTime: "10am",
        closeTime: "10pm",
        categories: ["Drink", "Dance"],
    },
];
