import parmi from "../images/parmi.png";
import cocktail from "../images/cocktail.png";

export const specialshard = [
    {
        businessId: "1234",
        venue: "Torrens Arms",
        special: "2 for 1 Parmis",
        time: "6-10pm",
        location: "Mitcham, 5062, Adelaide",
        img: parmi,
    },
    {
        businessId: "12234",
        venue: "Marion Hoten",
        special: "$10 pints",
        time: "8-10pm",
        location: "Marion, 5362, Adelaide",
        img: parmi,
    },
    {
        businessId: "5434",
        venue: "The Bar",
        special: "Free cocktails",
        time: "6-7pm",
        location: "Norwood, 5060, Adelaide",
        img: cocktail,
    },
    {
        businessId: "1234",
        venue: "Torrens Arms",
        special: "2 for 1 Parmis",
        time: "6-10pm",
        location: "Mitcham, 5062, Adelaide",
        img: parmi,
    },
    {
        businessId: "12234",
        venue: "Marion Hoten",
        special: "$10 pints",
        time: "8-10pm",
        location: "Marion, 5362, Adelaide",
        img: parmi,
    },
    {
        businessId: "5434",
        venue: "The Bar",
        special: "Free cocktails",
        time: "6-7pm",
        location: "Norwood, 5060, Adelaide",
        img: cocktail,
    },
    {
        businessId: "12234",
        venue: "Marion Hoten",
        special: "$10 pints",
        time: "8-10pm",
        location: "Marion, 5362, Adelaide",
        img: parmi,
    },
    {
        businessId: "5434",
        venue: "The Bar",
        special: "Free cocktails",
        time: "6-7pm",
        location: "Norwood, 5060, Adelaide",
        img: cocktail,
    },
    {
        businessId: "12234",
        venue: "Marion Hoten",
        special: "$10 pints",
        time: "8-10pm",
        location: "Marion, 5362, Adelaide",
        img: parmi,
    },
    {
        businessId: "5434",
        venue: "The Bar",
        special: "Free cocktails",
        time: "6-7pm",
        location: "Norwood, 5060, Adelaide",
        img: cocktail,
    },
];
